[package]
name = "memnarch-rs"
version = "0.1.0"
authors = ["Mendess2526 <pedro.mendes.26@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "*"
serde = "*"
serde_json ="*"
itertools = "0.8"
rand = "0.7"
simsearch = "0.1.4"
regex = "1"
lazy_static = "1"

[dependencies.serenity]
version = "0.7.0"
features = ["framework", "standard_framework", "voice"]

[features]
nightly = []
