[package]
name = "memnarch-rs"
version = "0.1.0"
authors = ["Mendess2526 <pedro.mendes.26@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "*"
serde = "*"
serde_json ="*"
itertools = "0.8"

[dependencies.serenity]
version = "0.6.x"
git = "https://github.com/serenity-rs/serenity"
branch = "current"
features = ["framework", "standard_framework", "voice"]
