name: Test and Release

on:
  push:
    branches: [ master ]
    tags:
      - '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # - name: run tests
    #   run: cargo test
    - name: install cross
      run: cargo install cross
    - name: cross compile
      run: ./rpi-compile.sh
    - name: release
      uses: ncipollo/release-action@v1.8.6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: ./target/armv7-unknown-linux-gnueabihf/release/memnarch-rs
